// <auto-generated />
using System;
using MasterNet.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MasterNet.Persistence.Migrations
{
    [DbContext(typeof(MasterNetDbContext))]
    [Migration("20260414022022_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("MasterNet.Domain.Calificacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Alumno")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comentario")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CursoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Puntaje")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.ToTable("calificaciones", (string)null);
                });

            modelBuilder.Entity("MasterNet.Domain.Curso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaPublicacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("cursos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("03ac5227-4f65-4ab1-ba66-2f2d0390516a"),
                            Descripcion = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            FechaPublicacion = new DateTime(2025, 10, 27, 19, 27, 28, 202, DateTimeKind.Local).AddTicks(7609),
                            Titulo = "Awesome Frozen Mouse"
                        },
                        new
                        {
                            Id = new Guid("faadcbfa-6a7a-49d0-837c-b84b2b9bfd79"),
                            Descripcion = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            FechaPublicacion = new DateTime(2025, 6, 25, 19, 32, 42, 266, DateTimeKind.Local).AddTicks(5259),
                            Titulo = "Rustic Wooden Fish"
                        },
                        new
                        {
                            Id = new Guid("b44118a6-ce7b-4a55-b463-4c4d16513e08"),
                            Descripcion = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            FechaPublicacion = new DateTime(2025, 5, 29, 6, 51, 20, 918, DateTimeKind.Local).AddTicks(4260),
                            Titulo = "Tasty Frozen Chair"
                        },
                        new
                        {
                            Id = new Guid("34476689-242a-4d02-8a3f-6c5eee1a2310"),
                            Descripcion = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            FechaPublicacion = new DateTime(2025, 11, 13, 11, 29, 42, 236, DateTimeKind.Local).AddTicks(7933),
                            Titulo = "Fantastic Concrete Shoes"
                        },
                        new
                        {
                            Id = new Guid("80fba108-598e-4584-b620-fdecb0119602"),
                            Descripcion = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            FechaPublicacion = new DateTime(2025, 8, 29, 7, 59, 51, 529, DateTimeKind.Local).AddTicks(9900),
                            Titulo = "Practical Metal Shirt"
                        },
                        new
                        {
                            Id = new Guid("b396ac97-a118-4f47-a17c-ae0a41b9ea16"),
                            Descripcion = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            FechaPublicacion = new DateTime(2025, 12, 8, 18, 26, 47, 300, DateTimeKind.Local).AddTicks(9525),
                            Titulo = "Handcrafted Granite Pants"
                        },
                        new
                        {
                            Id = new Guid("a7e961b9-d8df-4dad-bf8f-df0de987c5d3"),
                            Descripcion = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            FechaPublicacion = new DateTime(2025, 9, 9, 1, 16, 9, 946, DateTimeKind.Local).AddTicks(894),
                            Titulo = "Handcrafted Frozen Towels"
                        },
                        new
                        {
                            Id = new Guid("3b1fb476-e2ac-4c89-a326-66a1ac807726"),
                            Descripcion = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            FechaPublicacion = new DateTime(2025, 6, 1, 17, 45, 34, 147, DateTimeKind.Local).AddTicks(3435),
                            Titulo = "Practical Soft Shoes"
                        },
                        new
                        {
                            Id = new Guid("e2c285a7-f395-4726-a6b5-d283fe124492"),
                            Descripcion = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            FechaPublicacion = new DateTime(2026, 3, 17, 23, 24, 25, 57, DateTimeKind.Local).AddTicks(2700),
                            Titulo = "Practical Soft Mouse"
                        },
                        new
                        {
                            Id = new Guid("8f998161-bfa8-4734-9b00-13236c260024"),
                            Descripcion = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            FechaPublicacion = new DateTime(2025, 4, 15, 20, 2, 45, 826, DateTimeKind.Local).AddTicks(7349),
                            Titulo = "Refined Rubber Fish"
                        });
                });

            modelBuilder.Entity("MasterNet.Domain.CursoInstructor", b =>
                {
                    b.Property<Guid>("CursoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InstructorId")
                        .HasColumnType("TEXT");

                    b.HasKey("CursoId", "InstructorId");

                    b.HasIndex("InstructorId");

                    b.ToTable("cursos_instructores", (string)null);
                });

            modelBuilder.Entity("MasterNet.Domain.CursoPrecio", b =>
                {
                    b.Property<Guid>("CursoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PrecioId")
                        .HasColumnType("TEXT");

                    b.HasKey("CursoId", "PrecioId");

                    b.HasIndex("PrecioId");

                    b.ToTable("cursos_precios", (string)null);
                });

            modelBuilder.Entity("MasterNet.Domain.Instructor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Apellidos")
                        .HasColumnType("TEXT");

                    b.Property<string>("Grado")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("instructores", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ad25a34d-6108-487b-93f9-a45ce1fefebe"),
                            Apellidos = "Mohr",
                            Grado = "Forward Applications Producer",
                            Nombre = "Kolby"
                        },
                        new
                        {
                            Id = new Guid("988bdb82-eca5-4001-91f9-34967d3b1c87"),
                            Apellidos = "Windler",
                            Grado = "Regional Program Architect",
                            Nombre = "Darryl"
                        },
                        new
                        {
                            Id = new Guid("40a56bb6-3b59-4617-b508-ae60d20a433c"),
                            Apellidos = "Olson",
                            Grado = "Senior Security Planner",
                            Nombre = "Andrew"
                        },
                        new
                        {
                            Id = new Guid("19349b32-a3f0-4461-ad8c-8b41dcb87294"),
                            Apellidos = "Sawayn",
                            Grado = "Legacy Response Liaison",
                            Nombre = "Pierre"
                        },
                        new
                        {
                            Id = new Guid("2379073a-efb3-4c4b-bba5-006909dbf56b"),
                            Apellidos = "Wiza",
                            Grado = "Human Optimization Developer",
                            Nombre = "Conrad"
                        },
                        new
                        {
                            Id = new Guid("7f12a9a5-2067-45aa-8831-057b5ec9a4b9"),
                            Apellidos = "Beier",
                            Grado = "Dynamic Marketing Analyst",
                            Nombre = "Regan"
                        },
                        new
                        {
                            Id = new Guid("384c9775-884f-4116-8705-f32f3ca9d004"),
                            Apellidos = "Von",
                            Grado = "Global Response Specialist",
                            Nombre = "Alexandra"
                        },
                        new
                        {
                            Id = new Guid("93ce3998-851b-4f24-9c70-6a31faf3f577"),
                            Apellidos = "Ward",
                            Grado = "Customer Usability Strategist",
                            Nombre = "Lera"
                        },
                        new
                        {
                            Id = new Guid("31ca3552-2e16-4eb9-87e9-e492bc69422b"),
                            Apellidos = "Tremblay",
                            Grado = "National Factors Associate",
                            Nombre = "Samir"
                        },
                        new
                        {
                            Id = new Guid("45e97544-db15-42ed-8a2b-37626398f503"),
                            Apellidos = "Macejkovic",
                            Grado = "Senior Usability Facilitator",
                            Nombre = "Kennedi"
                        });
                });

            modelBuilder.Entity("MasterNet.Domain.Photo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CursoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.ToTable("imagenes", (string)null);
                });

            modelBuilder.Entity("MasterNet.Domain.Precio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasMaxLength(250)
                        .HasColumnType("VARCHAR");

                    b.Property<decimal>("PrecioActual")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioPromocion")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("precios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("fbe60fc6-205d-4702-aa88-571c5975bea0"),
                            Nombre = "Precio regular",
                            PrecioActual = 10.00m,
                            PrecioPromocion = 8.00m
                        });
                });

            modelBuilder.Entity("MasterNet.Domain.Calificacion", b =>
                {
                    b.HasOne("MasterNet.Domain.Curso", "Curso")
                        .WithMany("Calificaciones")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("MasterNet.Domain.CursoInstructor", b =>
                {
                    b.HasOne("MasterNet.Domain.Curso", "Curso")
                        .WithMany("CursoInstructores")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MasterNet.Domain.Instructor", "Instructor")
                        .WithMany("CursoInstructores")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("MasterNet.Domain.CursoPrecio", b =>
                {
                    b.HasOne("MasterNet.Domain.Curso", "Curso")
                        .WithMany("CursoPrecios")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MasterNet.Domain.Precio", "Precio")
                        .WithMany("CursoPrecios")
                        .HasForeignKey("PrecioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Precio");
                });

            modelBuilder.Entity("MasterNet.Domain.Photo", b =>
                {
                    b.HasOne("MasterNet.Domain.Curso", "Curso")
                        .WithMany("Photos")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("MasterNet.Domain.Curso", b =>
                {
                    b.Navigation("Calificaciones");

                    b.Navigation("CursoInstructores");

                    b.Navigation("CursoPrecios");

                    b.Navigation("Photos");
                });

            modelBuilder.Entity("MasterNet.Domain.Instructor", b =>
                {
                    b.Navigation("CursoInstructores");
                });

            modelBuilder.Entity("MasterNet.Domain.Precio", b =>
                {
                    b.Navigation("CursoPrecios");
                });
#pragma warning restore 612, 618
        }
    }
}
